remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: 不常更新的排版技术笔记（极简版）
description: 外行经验（打工中）
author: Clerk Ma

social-network-links:
  email: "clerkma@gmail.com"
  twitter: clerk_ma
